# Generated by Django 5.2.6 on 2025-09-07 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CarStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_norm', models.CharField(max_length=100)),
                ('model_group_norm', models.CharField(max_length=100)),
                ('model_norm', models.CharField(max_length=100)),
                ('variant_norm', models.CharField(max_length=100)),
                ('model_group_raw', models.CharField(blank=True, max_length=100, null=True)),
                ('model_raw', models.CharField(blank=True, max_length=100, null=True)),
                ('variant_raw', models.CharField(blank=True, max_length=100, null=True)),
                ('variant_raw2', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cars_standard',
                'indexes': [models.Index(fields=['brand_norm', 'model_norm', 'variant_norm'], name='cars_standa_brand_n_557d55_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceHistoryUnified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('carlistmy', 'CarlistMY'), ('mudahmy', 'MudahMY')], default='carlistmy', max_length=20)),
                ('old_price', models.IntegerField(blank=True, null=True)),
                ('new_price', models.IntegerField()),
                ('listing_url', models.TextField()),
                ('changed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'price_history_unified',
                'indexes': [models.Index(fields=['listing_url', 'changed_at'], name='price_histo_listing_dac374_idx'), models.Index(fields=['changed_at'], name='price_histo_changed_4dbdcc_idx')],
                'unique_together': {('listing_url', 'changed_at')},
            },
        ),
        migrations.CreateModel(
            name='CarUnified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('carlistmy', 'CarlistMY'), ('mudahmy', 'MudahMY')], max_length=20)),
                ('listing_url', models.TextField()),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(max_length=100)),
                ('model_group', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(max_length=100)),
                ('variant', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, max_length=50, null=True)),
                ('seat_capacity', models.CharField(blank=True, max_length=10, null=True)),
                ('engine_cc', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('information_ads', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('ads_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_check', models.DateTimeField(blank=True, null=True)),
                ('information_ads_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cars_standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.carstandard')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'db_table': 'cars_unified',
                'indexes': [models.Index(fields=['source', 'listing_url'], name='cars_unifie_source_75c3b7_idx'), models.Index(fields=['brand', 'model'], name='cars_unifie_brand_1a6309_idx'), models.Index(fields=['price'], name='cars_unifie_price_e085ad_idx'), models.Index(fields=['year'], name='cars_unifie_year_af4266_idx'), models.Index(fields=['last_scraped_at'], name='cars_unifie_last_sc_47cb59_idx'), models.Index(fields=['information_ads_date'], name='cars_unifie_informa_779434_idx')],
                'unique_together': {('source', 'listing_url')},
            },
        ),
        migrations.CreateModel(
            name='BrandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'db_table': 'brand_categories',
                'unique_together': {('brand', 'category')},
            },
        ),
    ]
