# Generated by Django 5.2.6 on 2025-09-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'otp_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'created_at'], name='otp_session_phone_n_d8396a_idx'), models.Index(fields=['otp_code'], name='otp_session_otp_cod_88ac07_idx'), models.Index(fields=['is_used'], name='otp_session_is_used_2294d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerifiedPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number with country code (+60xxxxxxxxx or +62xxxxxxxxx)', max_length=15, unique=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True, help_text='First time verified')),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time accessed')),
                ('access_count', models.PositiveIntegerField(default=1, help_text='Number of times accessed')),
                ('is_active', models.BooleanField(default=True, help_text='Whether phone is still active')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device info', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Last IP address', null=True)),
            ],
            options={
                'db_table': 'verified_phones',
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['phone_number'], name='verified_ph_phone_n_317bb1_idx'), models.Index(fields=['verified_at'], name='verified_ph_verifie_13dc2c_idx'), models.Index(fields=['last_accessed'], name='verified_ph_last_ac_1c534c_idx'), models.Index(fields=['is_active'], name='verified_ph_is_acti_852b26_idx')],
            },
        ),
    ]
