# Generated by Django 5.2.6 on 2025-09-08 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_otpsession_verifiedphone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(help_text='Configuration name for identification', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=True, help_text='True = Draft, False = Published')),
                ('is_active', models.BooleanField(default=False, help_text='Currently active configuration')),
                ('layer1_max_reduction', models.DecimalField(decimal_places=2, default=15.0, help_text='Maximum reduction percentage for Layer 1 (Mileage)', max_digits=5)),
                ('layer2_max_reduction', models.DecimalField(decimal_places=2, default=70.0, help_text='Maximum reduction percentage for Layer 2 (Conditions)', max_digits=5)),
                ('total_max_reduction', models.DecimalField(decimal_places=2, default=85.0, help_text='Maximum total reduction percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_configs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pricing_configurations',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Layer2Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Exterior Condition')", max_length=100)),
                ('field_name', models.CharField(help_text='Form field name (auto-generated)', max_length=50)),
                ('icon_class', models.CharField(default='fas fa-cog', help_text='Font Awesome icon class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer2_conditions', to='main.pricingconfiguration')),
            ],
            options={
                'db_table': 'layer2_conditions',
                'ordering': ['order', 'name'],
                'unique_together': {('config', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='Layer1Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage_threshold_percent', models.DecimalField(decimal_places=2, default=10.0, help_text='Mileage threshold percentage (e.g., 10 = every 10% excess)', max_digits=5)),
                ('reduction_per_threshold', models.DecimalField(decimal_places=2, default=2.0, help_text='Reduction percentage per threshold (e.g., 2 = 2% reduction)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layer1_config', to='main.pricingconfiguration')),
            ],
            options={
                'db_table': 'layer1_configurations',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('published', 'Published'), ('deactivated', 'Deactivated'), ('deleted', 'Deleted')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('snapshot_data', models.JSONField(default=dict, help_text='JSON snapshot of configuration')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.pricingconfiguration')),
            ],
            options={
                'db_table': 'configuration_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConditionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Display label (e.g., 'Excellent', 'Good')", max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Reduction percentage', max_digits=5)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.layer2condition')),
            ],
            options={
                'db_table': 'condition_options',
                'ordering': ['order'],
                'unique_together': {('condition', 'label')},
            },
        ),
    ]
