# Generated by Django 5.2.6 on 2025-09-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_add_layer2_cap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationhistory',
            name='config',
        ),
        migrations.RemoveField(
            model_name='configurationhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='layer1configuration',
            name='config',
        ),
        migrations.AlterUniqueTogether(
            name='layer2condition',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='layer2condition',
            name='config',
        ),
        migrations.RemoveField(
            model_name='pricingconfiguration',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pricingconfiguration',
            name='updated_by',
        ),
        migrations.RemoveConstraint(
            model_name='conditionoption',
            name='main_conditionoption_category_id_label_c6f9e8bb_uniq',
        ),
        migrations.AddField(
            model_name='category',
            name='reduction_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Reduction percentage for this category (0-100%)', max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='conditionoption',
            unique_together={('category', 'label')},
        ),
        migrations.DeleteModel(
            name='ConfigurationHistory',
        ),
        migrations.DeleteModel(
            name='Layer1Configuration',
        ),
        migrations.DeleteModel(
            name='Layer2Condition',
        ),
        migrations.DeleteModel(
            name='PricingConfiguration',
        ),
    ]
