# Generated by Django 5.2.6 on 2025-09-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_configurationhistory_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='reduction_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Reduction percentage for this category (0-100%)', max_digits=5),
        ),
    ]
