# Generated by Django 5.2.6 on 2025-09-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_add_reduction_percentage_to_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tier name (e.g., 'Budget', 'Mid-range', 'Premium')", max_length=100, unique=True)),
                ('min_price', models.DecimalField(decimal_places=2, help_text='Minimum price for this tier (RM)', max_digits=12)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price for this tier (RM), leave blank for unlimited', max_digits=12, null=True)),
                ('reduction_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Reduction percentage for this price tier (0-100%)', max_digits=5)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'price_tiers',
                'ordering': ['order', 'min_price'],
            },
        ),
    ]
