# Generated by Django 5.2.6 on 2025-09-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_add_price_tier_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpsession',
            name='verification_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
