# Generated by Django 5.2.6 on 2025-09-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_otpsession_verification_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otpsession',
            name='otp_session_otp_cod_88ac07_idx',
        ),
        migrations.RemoveField(
            model_name='otpsession',
            name='otp_code',
        ),
        migrations.AddIndex(
            model_name='otpsession',
            index=models.Index(fields=['verification_id'], name='otp_session_verific_3cc544_idx'),
        ),
    ]
