# Generated by Django 5.2.6 on 2025-09-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_otpsession_otp_session_otp_cod_88ac07_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carunified',
            name='cars_standard',
        ),
        migrations.AlterUniqueTogether(
            name='carunified',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='carunified',
            name='category',
        ),
        migrations.DeleteModel(
            name='PriceHistoryUnified',
        ),
        migrations.DeleteModel(
            name='CarStandard',
        ),
        migrations.DeleteModel(
            name='CarUnified',
        ),
    ]
