# Generated by Django 5.2.6 on 2025-09-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_populate_current_custom_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number of user who made calculation', max_length=15)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('variant', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('user_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_reduction_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'calculation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='calculationlog',
            index=models.Index(fields=['phone_number'], name='calculation_phone_n_bf9853_idx'),
        ),
        migrations.AddIndex(
            model_name='calculationlog',
            index=models.Index(fields=['created_at'], name='calculation_created_52a9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='calculationlog',
            index=models.Index(fields=['brand', 'model'], name='calculation_brand_79dcec_idx'),
        ),
    ]
