# Generated by Django 5.2.6 on 2025-09-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20250922_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpsession',
            name='otp_code',
            field=models.CharField(blank=True, help_text='6-digit OTP code for CopyCode', max_length=6, null=True),
        ),
    ]
